### ISSUE TITLE
Exercise 11 -- Matching numerical values and event propogation

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/js_track#11]
https://github.com/segunadeleye/js_track/blob/master/Ex11/exercise_11.js

**Comment by jatin-baweja** [comment]
1. Code can be modularized.
2. Please use regex to check for numeric value.
3. Use DOM methods with element class/id, to fetch form and input fields

**Comment by segunadeleye** [comment]
#### FIxed!!!
- Created additional methods.
- Number validation now done with regex.
- `document.getElementById` now used for selecting `input` and `form`.

**Comment by jatin-baweja** [comment]
1. Use submit event for form instead of click event on button, we can submit by pressing enter.
2. Use regex to incorporate negative numbers and float numbers as well.
3. Instead of passing input to each method, it can be stored as a property of the class.
4. Regex can be stored in a separate constants object.

**Comment by segunadeleye** [comment]
#### Fixed!!!

**Comment by segunadeleye** [comment]
- submit event listener called on form.
- Regex now checks for negative numbers and floating numbers.
- text input now a property of the class.
- Regex stored in a constant object. I used Object.freeze() to make it immutable.
